# Generated by Django 5.2.9 on 2025-12-24 19:41

from django.db import migrations
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        VectorExtension(),
    ]
